### ISSUE TITLE
Dependencies TYPO3 (6.2.3 - 8.99.99) for Version 2.0.0 Beta

### ISSUE THREAD

**Issue by whiteroom** [astehlik/typo3-extension-tinyurls#10]
Enabling : Create speaking URLs [basic.createSpeakingURLs]
crashes on TYPO3 CMS 6.2.x

Reason: `makeInstance(MarkerBasedTemplateService::class)` fails in 6.2.x

We have to either change dependency from 6.2.3 to 7.5
or change line 157 in typo3conf/ext/tinyurls/Classes/Utils/UrlUtils.php

from `return GeneralUtility::makeInstance(MarkerBasedTemplateService::class);`
to `return GeneralUtility::makeInstance(HtmlParser::class);`

**Comment by astehlik** [comment]
Thank you for your input.

The support for 6.2 was dropped in the current develop branch. The requirements in `composer.json` and `ext_emconf.php` were adjusted accordingliny.
