### ISSUE TITLE
Please add psr-4-autoload entry in ext_emconf.php 

### ISSUE THREAD

**Issue by mediaessenz** [astehlik/typo3-extension-tinyurls#16]
```
'autoload' => array(
	'psr-4' => [
		'Tx\\Tinyurls\\' => 'Classes',
	],
),
```
Change vendor name "Tx" to something better (see #15 )

**Comment by astehlik** [comment]
Do you currently experience problems with autoloading in non Composer mode? Normally TYPO3 should be able to extract the autoload information from the composer.json file, even in non composer mode.

**Comment by mediaessenz** [comment]
See: http://insight.helhum.io/post/130876393595/how-to-configure-class-loading-for-extensions-in
especially the sentence:
Note: If you do so, newly added classes during development can be resolved automatically, without any further action! There is no need to update your class information files!

**Comment by astehlik** [comment]
Thanks for your information.

Below there is another interesting sentence:

> If your extension has a composer.json file already with a psr-4 or classmap autoload section, you are done. No further action is required.

When using PSR-4 for autoloading new classes are also detected automatically without further action (at least this is my experience).

If you do not experience any problems with class loading I would close this issue.

**Comment by mediaessenz** [comment]
Good to know :-)
In this case, please close this issue.
