### ISSUE TITLE
Support for multiple domains

### ISSUE THREAD

**Issue by astehlik** [astehlik/typo3-extension-tinyurls#2]
At the moment the URL shortener only supports one domain.

TODO: Check if support for multiple domains makes sense and how it can be implemented.

**Comment by astehlik** [comment]
_Updated by BENCH Artwork over 1 year ago_

Would be great to have the ability to set a domain for the tiny urls service to use the extension in a separate page tree with a short domain.

But the ability to use this tiny urls domain in typolink configuration of the main tree.

**Comment by stadtkonzeptbasel** [comment]
Any news on that? Would be great to have this feature!
