### ISSUE TITLE
Change viewhelper argument registration method

### ISSUE THREAD

**Issue by dogawaf** [astehlik/typo3-extension-tinyurls#21]
Support for arguments on the render() method of ViewHelpers has been deprecated.

https://docs.typo3.org/typo3cms/extensions/core/Changelog/9.0/Deprecation-81213-RenderMethodArgumentOnViewHelpersDeprecated.html

They should be registered with initializeArguments.

Also, the base class is deprecated, so the ViewHelper now needs to extend directly TYPO3Fluid base class, and to use renderStatic method.

https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/9.0/Breaking-82414-RemoveCMSBaseViewHelperClasses.html

**Comment by astehlik** [comment]
Thank you for your input. 

Your suggested changes are new in the develop branch :)
