### ISSUE TITLE
TYPO3 10 compatibility

### ISSUE THREAD

**Issue by dogawaf** [astehlik/typo3-extension-tinyurls#24]
Hello

First of all, thanks for your extension. It helps sharing pages on twitter!

Do you plan to make it compatible with TYPO3 10?

**Comment by msollmann** [comment]
I could also need a v10 version...

**Comment by webmaster-buw** [comment]
+1

**Comment by astehlik** [comment]
Thank you all for your patience. I'm sorry I kept you waiting so long.

A new version 10 release was just now published.

**Comment by webmaster-buw** [comment]
:thumbsup: :pray:
