### ISSUE TITLE
List module causes  ArgumentCountError

### ISSUE THREAD

**Issue by cvisys** [astehlik/typo3-extension-tinyurls#27]
When use the list module in TYPO3 10.4. using v10.0.0, you get the following error

`Too few arguments to function Tx\Tinyurls\Hooks\DatabaseRecordList::__construct(), 0 passed in /web/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3443 and exactly 1 expected`

Now the rest of the extension works just fine.

**Comment by astehlik** [comment]
Thank you for taking the time to create an issue.

Normally the DatabaseRecordList hook should be autowired with the new dependency injection of TYPO3 10:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/DependencyInjection/Index.html

Can you please try to clear the system caches? In my test environment the list module is working fine.

**Comment by cvisys** [comment]
Thanks for the reply.

Clearing the caching doesn't solve the problem.

But if I change the Services.php to
`$configurator->services()
        ->defaults()
        ->autowire()
        ->autoconfigure()
        ->set(ExtensionConfiguration::class, ExtensionConfiguration::class)
        ->set(DatabaseRecordList::class, DatabaseRecordList::class)
        ->set(GeneralUtilityWrapper::class, GeneralUtilityWrapper::class)
        ->set(UrlUtils::class, UrlUtils::class);`

Adding autoconfigure() it works.

**Comment by astehlik** [comment]
Thank you @cvisys for investigating this and providing a fix.

I published a new release (10.0.1) that contains your solution (available on Packagist, should soon be in TER).

Cheers
Alex
