### ISSUE TITLE
TYPO3 11 compatibility

### ISSUE THREAD

**Issue by mediaessenz** [astehlik/typo3-extension-tinyurls#28]
Are there any plans to make this extension TYPO3 11 compatible?

**Comment by Oktopuce** [comment]
Still no news for a TYPO3 V11 compatibility ?
I've seen that there is a branch "feature/typo3-11" but with only one commit.

**Comment by mediaessenz** [comment]
@Oktopuce You can use my fork, if you like: https://github.com/mediaessenz/typo3-extension-tinyurls/tree/feature/v11

**Comment by astehlik** [comment]
Sorry for the long delay here.

I finally had the time to release version 11 (and am also preparing a TYPO3 12 version).

Please let me know if you experience any problems.
