### ISSUE TITLE
Please give ready2use url when creating new tinyurl

### ISSUE THREAD

**Issue by p-Enzi** [astehlik/typo3-extension-tinyurls#3]
To use the tinyurl an editor has to copy the wished long url into the new tinyurl form.
On saving this long url he then can read the new tinyurl.
The ditor then has to remember the speakingurl he has to use and type this in where he wants to use it.

It would saving 90% of all this work if below the URL key in the BE form would appear the speakingurl
according to the active ###TYPO3_SITE_URL###goto/###TINY_URL_KEY### template.
So above the Target URL field there could be a field like this:
Use TinyURL (copy and paste)
http://mydomain.tld/goto/b-xyz4712

**Comment by astehlik** [comment]
Thanks your your request. Really makes sense :) I'll provide an update soon.

**Comment by astehlik** [comment]
This feature is now available for TYPO3 7 in the current master. Testing feedback welcome :)
