### ISSUE TITLE
Allow "URL key" in BE form to copy 

### ISSUE THREAD

**Issue by p-Enzi** [astehlik/typo3-extension-tinyurls#4]
Without being able to copy the URL key from the BE form the extensions is completely useless.
Do you expect any editor to retype this key ten times a day?

**Comment by astehlik** [comment]
You're right. This is not rellay usable. I'll change this as soon as possible.

**Comment by astehlik** [comment]
This feature is now available for TYPO3 7 in the current master. Testing feedback welcome :)
