### ISSUE TITLE
listdisplay-error with urldisplay

### ISSUE THREAD

**Issue by mxsteini** [astehlik/typo3-extension-tinyurls#8]
When adding "urldisplay" with "set Field" in list-view-mode, the backend strumbles and there no way to deselect it.
I added a dummyfield to the database to fix that.

**Comment by astehlik** [comment]
Thank you for the report.

I just pushed a new version to the develop branch that adds the dummy field as you suggested and has a hook for improving the rendering (the tinyurl is displayed in the list now).

I hope it works for you. If you think its fine I'll publish a new release.
