### ISSUE TITLE
Broken createSpeakingURLs functionality on the 1.0.1 tag on packagist

### ISSUE THREAD

**Issue by cvisys** [astehlik/typo3-extension-tinyurls#9]
The createSpeakingURLs functionality of the 1.0.1 version that is on packagist.org doesn't work.

`if ($this->configUtils->getExtensionConfigurationValue('createSpeakingURLs')) {`
`$tinyUrl = $this->urlUtils->generateTinyurlHash($tinyUrlKey);`
`} else {`

Should probably have been 
`if ($this->configUtils->getExtensionConfigurationValue('createSpeakingURLs')) {`
`$tinyUrl = $this->urlUtils->createSpeakingTinyUrl($tinyUrlKey);`
`} else {`

Could you make a 1.0.2 with a fix thanks.

**Comment by astehlik** [comment]
Thank you. Good point. I finally need to release a new major version with the new stuff.

But there is a hotfix for now releases as version 1.0.2 on Packagist.

You are also very welcome to checkout the current master. It should be stable and has nicer Backend forms. Please let me know if you experience any problems.

Cheers,
Alex

**Comment by cvisys** [comment]
Thanks
